# Generated by Django 2.1.7 on 2019-03-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('docid', models.IntegerField(db_column='docId', primary_key=True, serialize=False)),
                ('specialization', models.CharField(blank=True, max_length=30, null=True)),
                ('experience', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(db_column='feedbackId', primary_key=True, serialize=False)),
                ('averagerating', models.FloatField(blank=True, db_column='averageRating', null=True)),
                ('feedback', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageid', models.CharField(db_column='imageId', max_length=12, primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('totalnoofwhitespots', models.FloatField(blank=True, db_column='totalNoOfWhiteSpots', null=True)),
                ('totalwhitespotarea', models.FloatField(blank=True, db_column='totalWhiteSpotArea', null=True)),
                ('totalwhitespotlength', models.FloatField(blank=True, db_column='totalWhiteSpotLength', null=True)),
                ('totalwhitespotarealessthanthirtyfivepixel', models.FloatField(blank=True, db_column='totalWhiteSpotAreaLessThanThirtyFivePixel', null=True)),
                ('totalwhitespotareagreaterthanhundredpixel', models.FloatField(blank=True, db_column='totalWhiteSpotAreaGreaterThanHundredPixel', null=True)),
                ('maxwhitespotarea', models.FloatField(blank=True, db_column='maxWhiteSpotArea', null=True)),
                ('systempredictedstage', models.IntegerField(blank=True, db_column='systemPredictedStage', null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.IntegerField(db_column='patientId', primary_key=True, serialize=False)),
                ('bloodgroup', models.CharField(blank=True, db_column='bloodGroup', max_length=2, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportid', models.IntegerField(db_column='reportId', primary_key=True, serialize=False)),
                ('dateofreportgeneration', models.DateField(blank=True, db_column='dateOfReportGeneration', null=True)),
                ('report', models.CharField(blank=True, max_length=1000, null=True)),
                ('appointmentdate', models.DateField(blank=True, db_column='appointmentDate', null=True)),
                ('doctorpredictedstage', models.IntegerField(blank=True, db_column='doctorPredictedStage', null=True)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(db_column='userId', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dateofbirth', models.DateField(blank=True, db_column='dateOfBirth', null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneno', models.BigIntegerField(blank=True, db_column='phoneNo', null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
