# Generated by Django 2.1.7 on 2019-03-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0003_auto_20190323_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mainpatient',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='maintutorial',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
