# Generated by Django 2.1.7 on 2019-03-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0004_auto_20190328_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mainpatient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='maintutorial',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
