# Generated by Django 2.1.7 on 2019-03-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0005_auto_20190328_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
