# Generated by Django 2.1.7 on 2019-04-01 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0006_auto_20190329_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='totalnoofwhitespots',
        ),
        migrations.RemoveField(
            model_name='image',
            name='totalwhitespotareagreaterthanhundredpixel',
        ),
        migrations.RemoveField(
            model_name='image',
            name='totalwhitespotarealessthanthirtyfivepixel',
        ),
        migrations.AddField(
            model_name='doctor',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trialapp.User'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='docid',
            field=models.ForeignKey(blank=True, db_column='docId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trialapp.Doctor'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='pateintid',
            field=models.ForeignKey(blank=True, db_column='pateintId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trialapp.Patient'),
        ),
        migrations.AddField(
            model_name='image',
            name='minwhitespotarea',
            field=models.FloatField(blank=True, db_column='MinWhiteSpotArea', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='patientid',
            field=models.ForeignKey(blank=True, db_column='patientId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trialapp.Patient'),
        ),
        migrations.AddField(
            model_name='image',
            name='totalnumberofwhitespots',
            field=models.FloatField(blank=True, db_column='totalNumberOfWhiteSpots', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='totalwhiteareagreaterthanhundredpixel',
            field=models.FloatField(blank=True, db_column='totalWhiteAreaGreaterThanHundredPixel', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='totalwhiteareagreaterthanthirtyfivepixel',
            field=models.FloatField(blank=True, db_column='totalWhiteAreaGreaterThanThirtyFivePixel', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='totalwhitearealessthanthirtyfivepixel',
            field=models.FloatField(blank=True, db_column='totalWhiteAreaLessThanThirtyFivePixel', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='docid',
            field=models.ForeignKey(blank=True, db_column='docId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trialapp.Doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trialapp.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='docid',
            field=models.ForeignKey(blank=True, db_column='docId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trialapp.Doctor'),
        ),
        migrations.AddField(
            model_name='report',
            name='imageid',
            field=models.ForeignKey(blank=True, db_column='imageId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trialapp.Image'),
        ),
        migrations.AddField(
            model_name='report',
            name='patientid',
            field=models.ForeignKey(blank=True, db_column='patientId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trialapp.Patient', unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Not Set', max_length=32),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='docid',
            field=models.AutoField(db_column='docId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='\\OriginalImg.JPG', upload_to='ctimages/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageid',
            field=models.AutoField(db_column='imageId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='maxwhitespotarea',
            field=models.FloatField(blank=True, db_column='MaxWhiteSpotArea', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='systempredictedstage',
            field=models.CharField(blank=True, db_column='systemPredictedStage', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientid',
            field=models.AutoField(db_column='patientId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportid',
            field=models.AutoField(db_column='reportId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.AutoField(db_column='userId', primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'phoneno')},
        ),
    ]
