# Generated by Django 2.1.7 on 2019-04-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0007_auto_20190401_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='totalnumberofwhitespots',
            new_name='totalnoofwhitespots',
        ),
    ]
